/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package cn.ict.rcc.messaging;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum Action implements org.apache.thrift.TEnum {
  READROW(1),
  READSELECT(2),
  FETCHONE(3),
  FETCHALL(4),
  WRITE(5),
  ADDINTEGER(6),
  ADDDECIMAL(7),
  DELETE(8);

  private final int value;

  private Action(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static Action findByValue(int value) { 
    switch (value) {
      case 1:
        return READROW;
      case 2:
        return READSELECT;
      case 3:
        return FETCHONE;
      case 4:
        return FETCHALL;
      case 5:
        return WRITE;
      case 6:
        return ADDINTEGER;
      case 7:
        return ADDDECIMAL;
      case 8:
        return DELETE;
      default:
        return null;
    }
  }
}
