/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package cn.ict.rcc.messaging;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class Graph implements org.apache.thrift.TBase<Graph, Graph._Fields>, java.io.Serializable, Cloneable, Comparable<Graph> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("Graph");

  private static final org.apache.thrift.protocol.TField VERTEXES_FIELD_DESC = new org.apache.thrift.protocol.TField("vertexes", org.apache.thrift.protocol.TType.MAP, (short)1);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new GraphStandardSchemeFactory());
    schemes.put(TupleScheme.class, new GraphTupleSchemeFactory());
  }

  public Map<String,Set<Node>> vertexes; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    VERTEXES((short)1, "vertexes");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // VERTEXES
          return VERTEXES;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.VERTEXES, new org.apache.thrift.meta_data.FieldMetaData("vertexes", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.MapMetaData(org.apache.thrift.protocol.TType.MAP, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING), 
            new org.apache.thrift.meta_data.SetMetaData(org.apache.thrift.protocol.TType.SET, 
                new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, Node.class)))));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(Graph.class, metaDataMap);
  }

  public Graph() {
  }

  public Graph(
    Map<String,Set<Node>> vertexes)
  {
    this();
    this.vertexes = vertexes;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public Graph(Graph other) {
    if (other.isSetVertexes()) {
      Map<String,Set<Node>> __this__vertexes = new HashMap<String,Set<Node>>(other.vertexes.size());
      for (Map.Entry<String, Set<Node>> other_element : other.vertexes.entrySet()) {

        String other_element_key = other_element.getKey();
        Set<Node> other_element_value = other_element.getValue();

        String __this__vertexes_copy_key = other_element_key;

        Set<Node> __this__vertexes_copy_value = new HashSet<Node>(other_element_value.size());
        for (Node other_element_value_element : other_element_value) {
          __this__vertexes_copy_value.add(new Node(other_element_value_element));
        }

        __this__vertexes.put(__this__vertexes_copy_key, __this__vertexes_copy_value);
      }
      this.vertexes = __this__vertexes;
    }
  }

  public Graph deepCopy() {
    return new Graph(this);
  }

  @Override
  public void clear() {
    this.vertexes = null;
  }

  public int getVertexesSize() {
    return (this.vertexes == null) ? 0 : this.vertexes.size();
  }

  public void putToVertexes(String key, Set<Node> val) {
    if (this.vertexes == null) {
      this.vertexes = new HashMap<String,Set<Node>>();
    }
    this.vertexes.put(key, val);
  }

  public Map<String,Set<Node>> getVertexes() {
    return this.vertexes;
  }

  public Graph setVertexes(Map<String,Set<Node>> vertexes) {
    this.vertexes = vertexes;
    return this;
  }

  public void unsetVertexes() {
    this.vertexes = null;
  }

  /** Returns true if field vertexes is set (has been assigned a value) and false otherwise */
  public boolean isSetVertexes() {
    return this.vertexes != null;
  }

  public void setVertexesIsSet(boolean value) {
    if (!value) {
      this.vertexes = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case VERTEXES:
      if (value == null) {
        unsetVertexes();
      } else {
        setVertexes((Map<String,Set<Node>>)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case VERTEXES:
      return getVertexes();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case VERTEXES:
      return isSetVertexes();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof Graph)
      return this.equals((Graph)that);
    return false;
  }

  public boolean equals(Graph that) {
    if (that == null)
      return false;

    boolean this_present_vertexes = true && this.isSetVertexes();
    boolean that_present_vertexes = true && that.isSetVertexes();
    if (this_present_vertexes || that_present_vertexes) {
      if (!(this_present_vertexes && that_present_vertexes))
        return false;
      if (!this.vertexes.equals(that.vertexes))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  @Override
  public int compareTo(Graph other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetVertexes()).compareTo(other.isSetVertexes());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetVertexes()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.vertexes, other.vertexes);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("Graph(");
    boolean first = true;

    sb.append("vertexes:");
    if (this.vertexes == null) {
      sb.append("null");
    } else {
      sb.append(this.vertexes);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    if (vertexes == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'vertexes' was not present! Struct: " + toString());
    }
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class GraphStandardSchemeFactory implements SchemeFactory {
    public GraphStandardScheme getScheme() {
      return new GraphStandardScheme();
    }
  }

  private static class GraphStandardScheme extends StandardScheme<Graph> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, Graph struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // VERTEXES
            if (schemeField.type == org.apache.thrift.protocol.TType.MAP) {
              {
                org.apache.thrift.protocol.TMap _map24 = iprot.readMapBegin();
                struct.vertexes = new HashMap<String,Set<Node>>(2*_map24.size);
                for (int _i25 = 0; _i25 < _map24.size; ++_i25)
                {
                  String _key26;
                  Set<Node> _val27;
                  _key26 = iprot.readString();
                  {
                    org.apache.thrift.protocol.TSet _set28 = iprot.readSetBegin();
                    _val27 = new HashSet<Node>(2*_set28.size);
                    for (int _i29 = 0; _i29 < _set28.size; ++_i29)
                    {
                      Node _elem30;
                      _elem30 = new Node();
                      _elem30.read(iprot);
                      _val27.add(_elem30);
                    }
                    iprot.readSetEnd();
                  }
                  struct.vertexes.put(_key26, _val27);
                }
                iprot.readMapEnd();
              }
              struct.setVertexesIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, Graph struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.vertexes != null) {
        oprot.writeFieldBegin(VERTEXES_FIELD_DESC);
        {
          oprot.writeMapBegin(new org.apache.thrift.protocol.TMap(org.apache.thrift.protocol.TType.STRING, org.apache.thrift.protocol.TType.SET, struct.vertexes.size()));
          for (Map.Entry<String, Set<Node>> _iter31 : struct.vertexes.entrySet())
          {
            oprot.writeString(_iter31.getKey());
            {
              oprot.writeSetBegin(new org.apache.thrift.protocol.TSet(org.apache.thrift.protocol.TType.STRUCT, _iter31.getValue().size()));
              for (Node _iter32 : _iter31.getValue())
              {
                _iter32.write(oprot);
              }
              oprot.writeSetEnd();
            }
          }
          oprot.writeMapEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class GraphTupleSchemeFactory implements SchemeFactory {
    public GraphTupleScheme getScheme() {
      return new GraphTupleScheme();
    }
  }

  private static class GraphTupleScheme extends TupleScheme<Graph> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, Graph struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      {
        oprot.writeI32(struct.vertexes.size());
        for (Map.Entry<String, Set<Node>> _iter33 : struct.vertexes.entrySet())
        {
          oprot.writeString(_iter33.getKey());
          {
            oprot.writeI32(_iter33.getValue().size());
            for (Node _iter34 : _iter33.getValue())
            {
              _iter34.write(oprot);
            }
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, Graph struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      {
        org.apache.thrift.protocol.TMap _map35 = new org.apache.thrift.protocol.TMap(org.apache.thrift.protocol.TType.STRING, org.apache.thrift.protocol.TType.SET, iprot.readI32());
        struct.vertexes = new HashMap<String,Set<Node>>(2*_map35.size);
        for (int _i36 = 0; _i36 < _map35.size; ++_i36)
        {
          String _key37;
          Set<Node> _val38;
          _key37 = iprot.readString();
          {
            org.apache.thrift.protocol.TSet _set39 = new org.apache.thrift.protocol.TSet(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
            _val38 = new HashSet<Node>(2*_set39.size);
            for (int _i40 = 0; _i40 < _set39.size; ++_i40)
            {
              Node _elem41;
              _elem41 = new Node();
              _elem41.read(iprot);
              _val38.add(_elem41);
            }
          }
          struct.vertexes.put(_key37, _val38);
        }
      }
      struct.setVertexesIsSet(true);
    }
  }

}

